# Setup
title:               Remy Kim
tagline:             '@StochasticRemy'
description:         'Stochastic is Yours'
url:                 'http://remyjkim.github.io'
baseurl:             '/remyjkim.com'
root:                '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Remy K
  url:               https://twitter.com/stochasticremy
  email:             remyjkim8@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
  date-format: '%b %d %y'

include:
  - .htaccess
  - _pages
  - files

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
